### PR TITLE
Add onIntent callback for ProgressBar Component

### PR DESCRIPTION
**Pull request by JemarJones**
Useful if you need to show some information about the time (or whatever) that is about to be seeked to. Updated tests and readme as well.

### CODE REVIEW

**Comment by alexanderwallin** [comment]
Brilliant! Looks good to the eye. I'll pull it down and have a proper look as soon as I can. If you'd like, it would be nice to have the demo page showcase the `onIntent` callback in the `<ProgressBar>` demo, although it's not a requirement for merging this PR.

**Comment by JemarJones** [comment]
Updated the docs with an example!

**Comment by alexanderwallin** [comment]
Fantastic. Thank you Jemar!

**Comment by alexanderwallin** [comment]
https://github.com/alexanderwallin/react-player-controls/releases/tag/v0.5.15

**Comment by JemarJones** [comment]
No problem, thanks so much for the quick release!

**Pull request merged**
